# Generated by Django 4.2.5 on 2023-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('jan', models.FloatField()),
                ('feb', models.FloatField()),
                ('mar', models.FloatField()),
                ('apr', models.FloatField()),
                ('may', models.FloatField()),
                ('jun', models.FloatField()),
                ('jul', models.FloatField()),
                ('aug', models.FloatField()),
                ('sep', models.FloatField()),
                ('oct', models.FloatField()),
                ('nov', models.FloatField()),
                ('dec', models.FloatField()),
                ('win', models.FloatField()),
                ('spr', models.FloatField()),
                ('sum', models.FloatField()),
                ('aut', models.FloatField()),
                ('ann', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
